# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Ikhwan Kim"

author:
  facebook:         duo830210
  twitter:          duo830210
  github:           duo821228
  stackoverflow:    your-id
  linkedin:         ikhwan-kim-5966b795
  reddit:           your-id
  tumblr:           your-id
  email:            ihkim@uos.ac.kr

copyright:
  year:             2018
  name:             Ikhwan Kim

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "ikhwankim"

# URL
url:                "https://duo821228.github.io" # the base hostname & protocol for your site
#url:                "https://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog
#baseurl:            "/Kiko-plus" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/duo821228"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]
